---
- name: Lay down docker-machine binary and completion script
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    checksum: "sha256:{{ item.hash }}"
  with_items:
    - url: "{{ docker_machine_url }}"
      dest: "{{ docker_machine_binary }}"
      hash: "{{docker_machine_hashes[docker_machine_version][ansible_system+'-'+ansible_architecture]}}"
    - url: "{{ docker_machine_bash_url }}"
      dest: /etc/bash_completion.d/docker-machine
      hash: "{{ docker_machine_bash_hash }}"

- name: Set docker-machine as executable
  file:
    state: file
    path: "{{ docker_machine_binary }}"
    mode: "u+x,g+x,o+x"
